### PUT update patient
PUT http://localhost:4000/patients/
Content-Type: application/json

{
  "name": "Patryk Sobow AAAA",
  "email": "patrykAAAA@gmail.com",
  "address": "main street 1",
  "dateOfBirth": "1999-01-01"
}

###